%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\denis\Documents\Processing\work\threeAS\AS3out-13-23-56.csv
%
% Auto-generated by MATLAB on 14-Apr-2020 16:43:42

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["picture", "stimulus", "correctresponse", "distance", "emotion", "answer", "RT", "correct"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, [1, 2], "TrimNonNumeric", true);
opts = setvaropts(opts, [1, 2], "ThousandsSeparator", ",");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
AS3out132356 = readtable("C:\Users\denis\Documents\Processing\work\threeAS\AS3out-13-23-56.csv", opts);


%% Clear temporary variables
clear opts